name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    tags:
      - "*" # Trigger on any Git tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies and build the Vue.js app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub (or another container registry)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Determine the Docker tags
      - name: Set Docker tags
        id: docker-tags
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            younntone/datav-tb-edge:latest
            younntone/datav-tb-edge:${{ env.TAG }}
          files: |
            dist
